### ISSUE TITLE
Question: implement as package provider?

### ISSUE THREAD

**Issue by faxm0dem** [meltwater/puppet-cpan#11]
This is just a question: wouldn't it be more natural to implement this as a package provider?

```
package { 'Foo::Bar':
  ensure   => latest,
  provider => 'cpan',
}
```

**Comment by salimane** [comment]
@faxm0dem pull requests are still welcomed

**Comment by faxm0dem** [comment]
:-) I'm still interested in doing this thanks for reminding me

**Comment by faxm0dem** [comment]
sorry, time doesn't permit this as of now. I'll close this and open a PR eventually
