### ISSUE TITLE
Quotes around case options

### ISSUE THREAD

**Issue by geekygnr** [meltwater/puppet-cpan#23]
I have been going over the git logs and this seems to be something that has flip flopped.

In manifests/init.pp the operating system names in the case statement are no longer in quotes (they were removed in commit 2da0666f90519518a56513c0aeb7ca25b3f0bcc0

Before that the quotes were added in commit a17ae4a7dff16af67d4f474f8cd2b544a6714d5c

I use puppet 3.8 in Debian 7 and as soon as I change the puppet configuration to have `parser = future` not having the quotes breaks the module.

**Comment by salimane** [comment]
a new version v2.0.0 has been published at https://forge.puppet.com/meltwater/cpan .
Thanks
