### ISSUE TITLE
`force` default bug

### ISSUE THREAD

**Issue by alexjfisher** [meltwater/puppet-cpan#41]
The `force` parameter defaults to the symbol `:false`.
https://github.com/meltwater/puppet-cpan/blob/c8aee48038dd8d8a6df23eb0a351589a72adf438/lib/puppet/type/cpan.rb#L33

The provider code checks whether the parameter equals the boolean `false`.
https://github.com/meltwater/puppet-cpan/blob/c8aee48038dd8d8a6df23eb0a351589a72adf438/lib/puppet/provider/cpan/default.rb#L35

This means that, by default, the force option `CPAN::force` is used.

**Comment by alexjfisher** [comment]
It would have worked before https://github.com/meltwater/puppet-cpan/commit/59a1acfe5e560687da923dbf345bad829d407d35

By removing `:parent => Puppet::Parameter::Boolean`, `:force` is no longer munged into `false` here https://github.com/puppetlabs/puppet/blob/8f0adfc55455aceff5c1ac2b416e16bc964c4e23/lib/puppet/coercion.rb#L24  and `if resource[:force] == false` in the provider no longer works.

**Comment by salimane** [comment]
@alexjfisher should this be closed ?

**Comment by alexjfisher** [comment]
Yes.  Thanks for merging my PR.
